# Starter pipeline
- task: CmdLine@2
  inputs:
    script: 'https://github.com/DeepaS123/Azurepipeline/blob/main/User_Interface.py'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
